# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables to ensure Python outputs all logs to the terminal without buffering
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's code into the container at /app
COPY . /app/

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define the command to run your application
# This can be a gunicorn command for production or the Django development server for development
CMD ["gunicorn", "website.wsgi:application", "--bind", "0.0.0.0:8000"]
# For development, you might use:
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]